import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import QueryProviders from "@/app/QueryProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({children}: Readonly<{children: ReactNode}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <QueryProviders>
          {children}
        </QueryProviders>
      </body>
    </html>
  );
}
